name: Termux Package Builder

env:
  TG_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  TG_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

on:
  workflow_dispatch:

jobs:
  termux_package_builder:
    name: Termux Package Builder
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Go to Home Directory
        run: cd ~

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull Docker container
        run: |
          docker pull ghcr.io/termux/package-builder:latest

      - name: Set up environment variables
        run: |
          echo "TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> $GITHUB_ENV
          echo "CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> $GITHUB_ENV

      - name: Start Building Termux Package
        run: |
          bash oneshot.sh
